// packages/mini-vue/demo/src/App.jsx
import { ref, effect, h } from '../../src'
import Child from './child'
export default {
  setup() {
    const count = ref(0)

    const add = () => {
      count.value++
      console.log('add clicked:',count)
    }
    console.log('setup running')
    effect(function log() {
      console.log('count changed!', count.value)
    })
    return () => (
      <div>
        <h1>mini-vue counter {Math.random()}</h1>
        <span>{count.value}</span>
        <button onClick={add}>+1</button>
        {/* <Child></Child> */}
      </div>
    )
  }
}

// packages/mini-vue/demo/src/App.vue
<template>
  <div>
    <h1>vue3</h1>
    <span>{{count}}</span>
    <button @click="add"> +1 </button>
  </div>
</template>
<script>
import { ref, effect } from 'vue'
export default {
  setup() {
    const count = ref(0)

    const add = () => count.value++
    console.log('setup running')
    effect(function log() {
      console.log('count changed!', count.value)
    })

    return { count, add }
  }
}
</script>
